from __future__ import annotations

import json
import re
import shutil
import tempfile
import uuid
from pathlib import Path


GENERATED_MARKER = ".generated-by-rizome-sync"
SKILL_MARKER_CONTENT = (
    "This directory is generated by scripts/sync-agent-skills.py.\n\n"
    "Canonical source:\nIA/skills/\n\n"
    "Do not edit Skills in this directory directly.\n"
    "Modify the canonical Skill under IA/skills/ instead.\n"
)
PROMPT_MARKER_CONTENT = (
    "This directory is generated by scripts/sync-agent-skills.py.\n\n"
    "Canonical source:\nIA/prompts/\n\n"
    "Do not edit prompts in this directory directly.\n"
    "Modify the canonical prompt under IA/prompts/ instead.\n"
)
LEGACY_PROMPT_MARKER_CONTENT = (
    "This directory is generated by scripts/sync-agent-skills.py.\n\n"
    "Canonical source:\nprompts/\n\n"
    "Do not edit prompts in this directory directly.\n"
    "Modify the canonical prompt under prompts/ instead.\n"
)


def prompt_name(prompt_file: Path, agent: str) -> str:
    if agent == "copilot":
        return prompt_file.name
    return prompt_file.name.removesuffix(".prompt.md") + ".md"


def prompt_projection_content(prompt_file: Path, agent: str) -> str:
    if agent == "copilot":
        lines = prompt_file.read_text(encoding="utf-8").splitlines()
        if not lines or lines[0] != "---":
            raise ValueError(f"Copilot prompt is missing YAML frontmatter: {prompt_file}")
        try:
            closing_line = lines.index("---", 1)
        except ValueError as error:
            raise ValueError(f"Copilot prompt has unterminated YAML frontmatter: {prompt_file}") from error

        content = "\n".join(lines[closing_line + 1:])
        has_source = "${input:source}" in content
        has_node = "${input:node}" in content
        if has_source == has_node:
            raise ValueError(f"Copilot prompt must define exactly one supported input: {prompt_file}")

        input_name = "node" if has_node else "source"
        input_label = (
            "The node and source provided by the user are:"
            if has_node
            else "The source provided by the user is:"
        )
        body = (
            f"Use the canonical prompt at [IA/prompts/{prompt_file.name}]"
            f"(../../IA/prompts/{prompt_file.name}) and execute its instructions.\n\n"
            f"{input_label}\n\n${{input:{input_name}}}"
        )
        frontmatter = "\n".join(lines[:closing_line + 1])
        return f"{frontmatter}\n\n{body}\n"

    if agent == "claude":
        return (
            f"Use the canonical instructions in `IA/prompts/{prompt_file.name}` "
            "for this request: $ARGUMENTS\n\n"
            "Load and follow the linked canonical prompt as the full task specification.\n"
        )
    if agent == "codex":
        return (
            f"Use the canonical instructions in `IA/prompts/{prompt_file.name}`.\n\n"
            "Execute those canonical instructions against the source or request supplied by the user.\n"
        )
    raise ValueError(f"Unsupported agent: {agent}")


def prompt_projection_is_valid(target: Path, source: Path, agent: str) -> bool:
    if not target.is_file():
        return False
    try:
        expected = prompt_projection_content(source, agent)
    except (OSError, ValueError):
        return False
    return target.read_text(encoding="utf-8") == expected


def marker_matches(target_root: Path, accepted_contents: str | tuple[str, ...]) -> bool:
    marker = target_root / GENERATED_MARKER
    if not marker.is_file():
        return False
    try:
        content = marker.read_text(encoding="utf-8")
    except OSError:
        return False
    accepted = (accepted_contents,) if isinstance(accepted_contents, str) else accepted_contents
    return content in accepted


def remove_generated_directory(
    target_root: Path, accepted_marker_contents: str | tuple[str, ...]
) -> bool:
    if not target_root.exists():
        return True
    if target_root.is_symlink() or not target_root.is_dir():
        return False
    if not marker_matches(target_root, accepted_marker_contents):
        return False
    shutil.rmtree(target_root)
    return True


def replace_generated_directory(source: Path, target: Path) -> None:
    staging = Path(tempfile.mkdtemp(prefix=f".{target.name}.sync-", dir=target.parent))
    backup = target.with_name(f".{target.name}.backup-{uuid.uuid4().hex}")
    moved_old_target = False
    try:
        shutil.copytree(source, staging, dirs_exist_ok=True)
        if target.exists():
            target.replace(backup)
            moved_old_target = True
        try:
            staging.replace(target)
        except OSError:
            if moved_old_target and backup.exists():
                backup.replace(target)
                moved_old_target = False
            raise
        if moved_old_target:
            shutil.rmtree(backup)
    finally:
        if staging.exists():
            shutil.rmtree(staging)


def is_exact_legacy_projection(directory: Path, canonical_skills: dict[str, Path]) -> bool:
    nested_skill_files = [
        path for path in directory.rglob("SKILL.md") if path.is_file()
    ]
    if not nested_skill_files:
        return False

    skill_directories = {path.parent for path in nested_skill_files}
    expected_files: set[Path] = set()
    expected_directories: set[Path] = set()

    for target_skill in skill_directories:
        source_skill = canonical_skills.get(target_skill.name)
        if source_skill is None or not source_skill.is_dir():
            return False
        source_files = {
            path.relative_to(source_skill)
            for path in source_skill.rglob("*")
            if path.is_file() and not path.is_symlink()
        }
        target_files = {
            path.relative_to(target_skill)
            for path in target_skill.rglob("*")
            if path.is_file() and not path.is_symlink()
        }
        if source_files != target_files:
            return False
        if any(path.is_symlink() for path in target_skill.rglob("*")):
            return False
        if any(
            (source_skill / relative).read_bytes() != (target_skill / relative).read_bytes()
            for relative in source_files
        ):
            return False
        for relative in source_files:
            projected_file = target_skill / relative
            expected_files.add(projected_file.relative_to(directory))
            parent = projected_file.parent
            while parent != directory:
                expected_directories.add(parent.relative_to(directory))
                parent = parent.parent

    actual_files = {
        path.relative_to(directory)
        for path in directory.rglob("*")
        if path.is_file()
    }
    actual_directories = {
        path.relative_to(directory)
        for path in directory.rglob("*")
        if path.is_dir()
    }
    if any(path.is_symlink() for path in directory.rglob("*")):
        return False
    return actual_files == expected_files and actual_directories == expected_directories


def validate_skill_frontmatter(skill_file: Path) -> list[str]:
    lines = skill_file.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        return ["missing YAML frontmatter"]
    try:
        closing_line = lines.index("---", 1)
    except ValueError:
        return ["unterminated YAML frontmatter"]

    metadata: dict[str, str] = {}
    errors: list[str] = []
    for line in lines[1:closing_line]:
        match = re.fullmatch(r"([A-Za-z0-9_-]+):\s*(.*?)\s*", line)
        if not match:
            continue
        key, raw_value = match.groups()
        if key not in {"name", "description"}:
            continue
        if key in metadata:
            errors.append(f"duplicate {key} metadata")
            continue
        try:
            if raw_value.startswith('"'):
                value = json.loads(raw_value)
                if not isinstance(value, str):
                    raise ValueError
            elif raw_value.startswith("'") and raw_value.endswith("'"):
                value = raw_value[1:-1].replace("''", "'")
            else:
                value = raw_value
        except (json.JSONDecodeError, ValueError):
            errors.append(f"invalid {key} scalar")
            continue
        metadata[key] = value

    expected_name = skill_file.parent.name
    if metadata.get("name") != expected_name:
        errors.append(f"name must be {expected_name!r}")
    if not metadata.get("description", "").strip():
        errors.append("description must be non-empty")
    return errors


def resolve_internal_reference(source_file: Path, reference: str, repository_root: Path) -> Path:
    canonical_root = repository_root / "IA"
    reference = reference.lstrip("/")
    while reference.startswith(("../", "./")):
        reference = reference[3:] if reference.startswith("../") else reference[2:]
    if reference.startswith(("IA/", ".github/", ".claude/", ".agents/", ".codex/")):
        return repository_root / reference
    if source_file.is_relative_to(canonical_root):
        return canonical_root / reference
    return repository_root / reference


def extract_internal_references(text: str) -> list[str]:
    text_without_urls = re.sub(r"https?://[^\s)>]+", "", text)
    return re.findall(
        r"(?<![A-Za-z0-9_])(?:\.\./|\./|/)*(?:IA/)?(?:skills|schemas|agents|workflows|prompts|scripts|\.github|\.claude|\.agents|\.codex)/[A-Za-z0-9_./-]+",
        text_without_urls,
    )