from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_SKILLS = ROOT / "skills"

# Canonical Skills remain organized by family. Agent discovery directories are flat.
# Codex project Skills are exposed through .agents/skills.
TARGETS = {
    "copilot": ROOT / ".github" / "skills",
    "claude": ROOT / ".claude" / "skills",
    "codex": ROOT / ".agents" / "skills",
}

GENERATED_MARKER = ".generated-by-rizome-sync"


def discover_skills() -> list[Path]:
    if not CANONICAL_SKILLS.exists():
        return []
    skills = []
    for skill_file in CANONICAL_SKILLS.rglob("SKILL.md"):
        skill_dir = skill_file.parent
        if "_shared" in skill_dir.relative_to(CANONICAL_SKILLS).parts:
            continue
        skills.append(skill_dir)
    return sorted(skills)


def skill_name(skill_dir: Path) -> str:
    return skill_dir.name


def relative_canonical_path(skill_dir: Path) -> Path:
    return skill_dir.relative_to(CANONICAL_SKILLS)


def validate_skill_names(skills: list[Path]) -> bool:
    """Families are repository organization; agent projections are flat."""
    print("\n== Skill name validation ==")
    names: dict[str, list[Path]] = {}
    for skill in skills:
        names.setdefault(skill_name(skill), []).append(skill)
    valid = True
    for name, paths in sorted(names.items()):
        if len(paths) == 1:
            print(f"PASS     {name}")
            continue
        print(f"ERROR    Skill name collision: {name}")
        for path in paths:
            print(f"         - {relative_canonical_path(path)}")
        valid = False
    return valid


def validate_canonical_skills(skills: list[Path]) -> bool:
    print("\n== Canonical Skills ==")
    if not CANONICAL_SKILLS.exists() or not skills:
        print("ERROR    No canonical Skills found.")
        return False
    valid = True
    for skill in skills:
        if not (skill / "SKILL.md").is_file():
            print(f"ERROR    Missing SKILL.md: {relative_canonical_path(skill)}")
            valid = False
        else:
            print(f"PASS     {relative_canonical_path(skill)}")
    print(f"\nFound {len(skills)} canonical Skills.")
    return valid


def marker_path(target_root: Path) -> Path:
    return target_root / GENERATED_MARKER


def has_marker(target_root: Path) -> bool:
    return marker_path(target_root).is_file()


def write_marker(target_root: Path) -> None:
    target_root.mkdir(parents=True, exist_ok=True)
    marker_path(target_root).write_text(
        "This directory is generated by scripts/sync-agent-skills.py.\n\n"
        "Canonical source:\nskills/\n\n"
        "Do not edit Skills in this directory directly.\n"
        "Modify the canonical Skill under skills/ instead.\n",
        encoding="utf-8",
    )


def relative_files(directory: Path, exclude_marker: bool = False) -> set[Path]:
    if not directory.exists():
        return set()
    result = set()
    for path in directory.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(directory)
        if exclude_marker and relative == Path(GENERATED_MARKER):
            continue
        result.add(relative)
    return result


def directories_are_equal(source: Path, target: Path) -> bool:
    if not source.is_dir() or not target.is_dir():
        return False
    source_files = relative_files(source)
    target_files = relative_files(target, exclude_marker=True)
    if source_files != target_files:
        return False
    return all(
        filecmp.cmp(source / relative, target / relative, shallow=False)
        for relative in source_files
    )


def validate_target_root(target_root: Path) -> bool:
    if not target_root.exists():
        return True
    if not target_root.is_dir():
        print(f"ERROR    Target is not a directory: {target_root.relative_to(ROOT)}")
        return False
    if not has_marker(target_root):
        print(f"ERROR    Refusing to modify unmarked directory: {target_root.relative_to(ROOT)}")
        return False
    return True


def legacy_nested_dirs(target_root: Path, skills: list[Path]) -> list[Path]:
    """Find old family-nested projections, without touching arbitrary content."""
    expected = {skill_name(skill) for skill in skills}
    result = []
    if not target_root.exists():
        return result
    for child in target_root.iterdir():
        if not child.is_dir() or child.name == GENERATED_MARKER:
            continue
        if (child / "SKILL.md").is_file():
            continue
        nested = list(child.rglob("SKILL.md"))
        if nested and {p.parent.name for p in nested}.issubset(expected):
            result.append(child)
    return sorted(result)


def sync_target(name: str, target_root: Path, skills: list[Path], dry_run: bool = False) -> bool:
    print(f"\n== SYNC {name.upper()} ==")
    print(f"Target: {target_root.relative_to(ROOT)}")
    if not validate_target_root(target_root):
        return False
    if not dry_run:
        target_root.mkdir(parents=True, exist_ok=True)
        write_marker(target_root)

    for legacy in legacy_nested_dirs(target_root, skills):
        print(f"REMOVE   legacy nested projection {legacy.relative_to(ROOT)}")
        if not dry_run:
            shutil.rmtree(legacy)

    expected = {skill_name(skill) for skill in skills}
    existing = {
        child.name for child in target_root.iterdir()
        if child.is_dir() and child.name != GENERATED_MARKER and (child / "SKILL.md").is_file()
    } if target_root.exists() else set()

    for stale in sorted(existing - expected):
        target = target_root / stale
        print(f"REMOVE   {target.relative_to(ROOT)}")
        if not dry_run:
            shutil.rmtree(target)

    synchronized = unchanged = 0
    for source in skills:
        target = target_root / skill_name(source)
        if target.exists() and not target.is_dir():
            print(f"ERROR    Target path is not a directory: {target.relative_to(ROOT)}")
            return False
        if directories_are_equal(source, target):
            print(f"UNCHANGED {skill_name(source)}")
            unchanged += 1
            continue
        print(f"SYNC     {relative_canonical_path(source)} -> {target.relative_to(ROOT)}")
        if not dry_run:
            if target.exists():
                shutil.rmtree(target)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(source, target)
        synchronized += 1

    print(f"\n{len(skills)} Skills: {synchronized} synchronized, {unchanged} unchanged.")
    return True


def check_target(name: str, target_root: Path, skills: list[Path]) -> bool:
    print(f"\n== CHECK {name.upper()} ==")
    if not target_root.exists() or not has_marker(target_root):
        print(f"ERROR    Missing generated target: {target_root.relative_to(ROOT)}")
        return False
    expected = {skill_name(skill) for skill in skills}
    actual = {
        child.name for child in target_root.iterdir()
        if child.is_dir() and child.name != GENERATED_MARKER and (child / "SKILL.md").is_file()
    }
    valid = True
    for name_to_check in sorted(expected - actual):
        print(f"ERROR    Missing Skill: {name_to_check}")
        valid = False
    for name_to_check in sorted(actual - expected):
        print(f"ERROR    Unexpected Skill: {name_to_check}")
        valid = False
    for legacy in legacy_nested_dirs(target_root, skills):
        print(f"ERROR    Legacy nested Skill layout: {legacy.relative_to(ROOT)}")
        valid = False
    for source in skills:
        target = target_root / skill_name(source)
        if target.exists() and not directories_are_equal(source, target):
            print(f"ERROR    Out of sync: {skill_name(source)}")
            valid = False
    if valid:
        print(f"PASS     {len(skills)} Skills synchronized with flat discovery layout.")
    return valid


def clean_target(name: str, target_root: Path) -> bool:
    print(f"\n== CLEAN {name.upper()} ==")
    if not target_root.exists():
        return True
    if not has_marker(target_root):
        print(f"ERROR    Refusing to remove unmarked directory: {target_root.relative_to(ROOT)}")
        return False
    shutil.rmtree(target_root)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize canonical Skills with agent discovery directories.")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--agent", choices=["copilot", "claude", "codex", "all"], default="all")
    args = parser.parse_args()
    if args.check and args.clean or args.clean and args.dry_run:
        print("ERROR    Incompatible command-line options.")
        return 1
    skills = discover_skills()
    if not validate_canonical_skills(skills) or not validate_skill_names(skills):
        return 1
    targets = TARGETS if args.agent == "all" else {args.agent: TARGETS[args.agent]}
    success = True
    for name, target in targets.items():
        if args.check:
            result = check_target(name, target, skills)
        elif args.clean:
            result = clean_target(name, target)
        else:
            result = sync_target(name, target, skills, args.dry_run)
        success = result and success
    print("\n== RESULT ==")
    print("PASS     Synchronization completed successfully." if success else "ERROR    Synchronization failed.")
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
